convertMenuItem <- function(mi, tabName) {
  mi$children[[1]]$attribs['data-toggle'] = "tab"
  mi$children[[1]]$attribs['data-value']  = tabName
  mi
}

sidebarMenuUI <- sidebarMenu(id = "tabs",
  menuItem("Introduction", tabName = "introduction", icon = icon("question-circle")),
  convertMenuItem(menuItem("Main settings", tabName = "config", icon = icon("cog"),
                           sliderInput("nSpecies", label = "Species considered", min = 1, max = 3, value = 1),
                           sliderInput("nDataSts", label = "Transport datasets", min = 1, max = 12, value = 1),
                           tags$hr(),
                           radioButtons("Format", label = "Download files type",
                                        choices = list("PDF (vector graphics)" = ".pdf", "PNG (300 ppi bitmap)" = ".png")),
                           sliderInput("plotsW", label = "Figures width (mm)", min = 40, max = 300, value = 80),
                           sliderInput("plotsH", label = "Figures height (mm)", min = 40, max = 300, value = 60)),
                  tabName = "config"),
  menuItem("Calibration Models", tabName = "calib", icon = icon("signal")),
  menuItem("Data input and transformation", tabName = "datInput", icon = icon("exchange-alt")),
  menuItem("Transport experiments", icon = icon("hourglass-half"),
           menuSubItem("Single transport profiles", tabName = "sTrns"),
           menuSubItem("Permeability coefficients", tabName = "pCoef"),
           menuSubItem("Separation factors", tabName = "sepFctr"),
           menuSubItem("Reuse cycles", tabName = "rCycl"),
           menuSubItem("Species concentration", tabName = "spCnc")),
  menuItem("Example datasets", icon = icon("folder-open"), tabName = "exDat"),
  menuItem("Citation", tabName = "citation", icon = icon("creative-commons")),
  menuItem("transmem CRAN webpage", icon = icon("r-project"), href = "https://CRAN.R-project.org/package=transmem"),
  menuItem("Bug reports and suggestions", icon = icon("bug"), href = "https://github.com/Crparedes/transmem_shinyapp/issues"),
  menuItem("Github repository", icon = icon("github"), href = "https://github.com/Crparedes/transmem_shinyapp"),
  menuItem("Bibliography", tabName = "bibliography", icon = icon("book"))
)

tabItemsUI <- tabItems(
  tabItem(tabName = "introduction", h1('Introduction'), introductionModuleUI('introduction')),
  # Calibration methods
  tabItem(tabName = "calib", h1("Calibration models"),
          calibrationModuleUI('MainSpeciesCal'),
          conditionalPanel(condition = "input.nSpecies >= 2",
                           calibrationModuleUI('SeconSpeciesCal', label.1 = "Secondary")),
          conditionalPanel(condition = "input.nSpecies == 3",
                           calibrationModuleUI('TertiSpeciesCal', label.1 = "Tertiary"))),
  # Input and transform data
  tabItem(tabName = "datInput", h1("Data input and transformation"),
          fluidRow(inputDataModuleUI('MainDset1', value0 = 7),
                   conditionalPanel(condition = "input.nSpecies >= 2",
                                    inputDataModuleUI('SecDset1', Spc = "Secondary", value0 = 4)),
                   conditionalPanel(condition = "input.nSpecies == 3",
                                    inputDataModuleUI('TerDset1', Spc = "Tertiary", value0 = 4))),
          conditionalPanel(condition = 'input.nDataSts >= 2', {
            fluidRow(inputDataModuleUI('MainDset2', IntID = 2, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset2', Spc = "Secondary", IntID = 2, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset2', Spc = "Tertiary", IntID = 2, value0 = 4)))}),
          conditionalPanel(condition = 'input.nDataSts >= 3', {
            fluidRow(inputDataModuleUI('MainDset3', IntID = 3, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset3', Spc = "Secondary", IntID = 3, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset3', Spc = "Tertiary", IntID = 3, value0 = 4)))}),
          conditionalPanel(condition = 'input.nDataSts >= 4', {
            fluidRow(inputDataModuleUI('MainDset4', IntID = 4, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset4', Spc = "Secondary", IntID = 4, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset4', Spc = "Tertiary", IntID = 4, value0 = 4)))}),
          conditionalPanel(condition = 'input.nDataSts >= 5', {
            fluidRow(inputDataModuleUI('MainDset5', IntID = 5, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset5', Spc = "Secondary", IntID = 5, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset5', Spc = "Tertiary", IntID = 5, value0 = 4)))}),
          conditionalPanel(condition = 'input.nDataSts >= 6', {
            fluidRow(inputDataModuleUI('MainDset6', IntID = 6, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset6', Spc = "Secondary", IntID = 6, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset6', Spc = "Tertiary", IntID = 6, value0 = 4)))}),
          conditionalPanel(condition = 'input.nDataSts >= 7', {
            fluidRow(inputDataModuleUI('MainDset7', IntID = 7, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset7', Spc = "Secondary", IntID = 7, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset7', Spc = "Tertiary", IntID = 7, value0 = 4)))}),
          conditionalPanel(condition = 'input.nDataSts >= 8', {
            fluidRow(inputDataModuleUI('MainDset8', IntID = 8, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset8', Spc = "Secondary", IntID = 8, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset8', Spc = "Tertiary", IntID = 8, value0 = 4)))}),
          conditionalPanel(condition = 'input.nDataSts >= 9', {
            fluidRow(inputDataModuleUI('MainDset9', IntID = 9, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset9', Spc = "Secondary", IntID = 9, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset9', Spc = "Tertiary", IntID = 9, value0 = 4)))}),
          conditionalPanel(condition = 'input.nDataSts >= 10', {
            fluidRow(inputDataModuleUI('MainDset10', IntID = 10, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset10', Spc = "Secondary", IntID = 10, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset10', Spc = "Tertiary", IntID = 10, value0 = 4)))}),
          conditionalPanel(condition = 'input.nDataSts >= 10', {
            fluidRow(inputDataModuleUI('MainDset11', IntID = 11, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset11', Spc = "Secondary", IntID = 11, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset11', Spc = "Tertiary", IntID = 11, value0 = 4)))}),
          conditionalPanel(condition = 'input.nDataSts >= 12', {
            fluidRow(inputDataModuleUI('MainDset12', IntID = 12, value0 = 7),
                     conditionalPanel(condition = "input.nSpecies >= 2",
                                      inputDataModuleUI('SecDset12', Spc = "Secondary", IntID = 12, value0 = 4)),
                     conditionalPanel(condition = "input.nSpecies == 3",
                                      inputDataModuleUI('TerDset12', Spc = "Tertiary", IntID = 12, value0 = 4)))})
          ),
  # Transport experiments,
  tabItem(tabName = "sTrns", h1("Single transport profiles"),
          fluidRow(column(2, selectInput("trendM", label = "Model for the main species profiles",
                                         choices = list("Paredes et al." = 1, "Rodriguez de San Miguel et al." = 2,
                                                        "LOESS (non parametric)" = 3, "Linear" = 4, "No trend line" = 5)),
                          uiOutput("M.mdlStt")),
                   column(2, conditionalPanel(condition = "input.nSpecies >= 2",
                                              selectInput("trendS", label = "Model for the sec. species profiles",
                                                          choices = list("Paredes et al." = 1, 
                                                                         "Rodriguez de San Miguel et al." = 2,
                                                                         "LOESS (non parametric)" = 3,
                                                                         "Linear" = 4, "No trend line" = 5)),
                                              uiOutput("S.mdlStt"))),
                   column(2, conditionalPanel(condition = "input.nSpecies >= 3",
                                              selectInput("trendT", label = "Model for the tertiary species profiles",
                                                          choices = list("Paredes et al." = 1, 
                                                                         "Rodriguez de San Miguel et al." = 2,
                                                                         "LOESS (non parametric)" = 3,
                                                                         "Linear" = 4, "No trend line" = 5)),
                                              uiOutput("T.mdlStt"))),
                   column(2, h5('Be sure all data has been entered and transformated (when required) before proceed.'),
                          actionButton("plotTrPr", label = "Draw/redraw profiles", styleclass = 'primary'))),
          tags$hr(),
          profileModuleUI('transProf1'),
          conditionalPanel(condition = 'input.nDataSts >= 2', {profileModuleUI('transProf2', IntID = 2)}),
          conditionalPanel(condition = 'input.nDataSts >= 3', {profileModuleUI('transProf3', IntID = 3)}),
          conditionalPanel(condition = 'input.nDataSts >= 4', {profileModuleUI('transProf4', IntID = 4)}),
          conditionalPanel(condition = 'input.nDataSts >= 5', {profileModuleUI('transProf5', IntID = 5)}),
          conditionalPanel(condition = 'input.nDataSts >= 6', {profileModuleUI('transProf6', IntID = 6)}),
          conditionalPanel(condition = 'input.nDataSts >= 7', {profileModuleUI('transProf7', IntID = 7)}),
          conditionalPanel(condition = 'input.nDataSts >= 8', {profileModuleUI('transProf8', IntID = 8)}),
          conditionalPanel(condition = 'input.nDataSts >= 9', {profileModuleUI('transProf9', IntID = 9)}),
          conditionalPanel(condition = 'input.nDataSts >= 10', {profileModuleUI('transProf10', IntID = 10)}),
          conditionalPanel(condition = 'input.nDataSts >= 11', {profileModuleUI('transProf11', IntID = 11)}),
          conditionalPanel(condition = 'input.nDataSts >= 12', {profileModuleUI('transProf12', IntID = 12)})
          ),
  # Permeability coefficients
  tabItem(tabName = "pCoef", h1("Permeability coefficients"),
          fluidRow(column(2, numericInput("P.area", label = "Membrane area (cm^2)", value = 7.8, min = 0)),
                   column(2, numericInput("P.vol0", label = "Initial volume (cm^3)", value = 85, min = 0)),
                   column(2, h5('Be sure all data has been entered and transformated (when required) before proceed.'),
                          actionButton("calcPrCf", label = "Calculate/recalculate", styleclass = 'primary'))),
          tags$hr(),
          permCoefModuleUI('permCoef1'),
          conditionalPanel(condition = 'input.nDataSts >= 2', {permCoefModuleUI('permCoef2', IntID = 2)}),
          conditionalPanel(condition = 'input.nDataSts >= 3', {permCoefModuleUI('permCoef3', IntID = 3)}),
          conditionalPanel(condition = 'input.nDataSts >= 4', {permCoefModuleUI('permCoef4', IntID = 4)}),
          conditionalPanel(condition = 'input.nDataSts >= 5', {permCoefModuleUI('permCoef5', IntID = 5)}),
          conditionalPanel(condition = 'input.nDataSts >= 6', {permCoefModuleUI('permCoef6', IntID = 6)}),
          conditionalPanel(condition = 'input.nDataSts >= 7', {permCoefModuleUI('permCoef7', IntID = 7)}),
          conditionalPanel(condition = 'input.nDataSts >= 8', {permCoefModuleUI('permCoef8', IntID = 8)}),
          conditionalPanel(condition = 'input.nDataSts >= 9', {permCoefModuleUI('permCoef9', IntID = 9)}),
          conditionalPanel(condition = 'input.nDataSts >= 10', {permCoefModuleUI('permCoef10', IntID = 10)}),
          conditionalPanel(condition = 'input.nDataSts >= 11', {permCoefModuleUI('permCoef11', IntID = 11)}),
          conditionalPanel(condition = 'input.nDataSts >= 12', {permCoefModuleUI('permCoef12', IntID = 12)})),
  # Separation factor
  tabItem(tabName = "sepFctr", h1("Separation factors"), tags$hr(),
          conditionalPanel(condition = 'input.nSpecies == 1',
                           infoBox(width = 12, "More species required", color = Hcol('Tertiary')[2], icon = icon("eye-slash"),
                                   h4('Separation factor calculations require at least two species!'))), 
          conditionalPanel(condition = 'input.nSpecies >= 2', 
                           fluidRow(column(2, selectInput("SF.model", label = "Definition to use:", 
                                                          choices = list("Batch systems" = 1, "Continous systems" = 2))),
                                    column(2, h5('Be sure all data has been entered and transformated (if required).'),
                                           actionButton("calcSepFc", label = "Calculate and plot separation factors", 
                                                        styleclass = 'primary'))),
                           tags$hr(),
                           sepFactorModuleUI('sepFactor1'),
                           conditionalPanel(condition = 'input.nDataSts >= 2', {sepFactorModuleUI('sepFactor2', IntID = 2)}),
                           conditionalPanel(condition = 'input.nDataSts >= 3', {sepFactorModuleUI('sepFactor3', IntID = 3)}),
                           conditionalPanel(condition = 'input.nDataSts >= 4', {sepFactorModuleUI('sepFactor4', IntID = 4)}),
                           conditionalPanel(condition = 'input.nDataSts >= 5', {sepFactorModuleUI('sepFactor5', IntID = 5)}),
                           conditionalPanel(condition = 'input.nDataSts >= 6', {sepFactorModuleUI('sepFactor6', IntID = 6)}),
                           conditionalPanel(condition = 'input.nDataSts >= 7', {sepFactorModuleUI('sepFactor7', IntID = 7)}),
                           conditionalPanel(condition = 'input.nDataSts >= 8', {sepFactorModuleUI('sepFactor8', IntID = 8)}),
                           conditionalPanel(condition = 'input.nDataSts >= 9', {sepFactorModuleUI('sepFactor9', IntID = 9)}),
                           conditionalPanel(condition = 'input.nDataSts >= 10', {sepFactorModuleUI('sepFactor10', IntID = 10)}),
                           conditionalPanel(condition = 'input.nDataSts >= 11', {sepFactorModuleUI('sepFactor11', IntID = 11)}),
                           conditionalPanel(condition = 'input.nDataSts >= 12', {sepFactorModuleUI('sepFactor12', IntID = 12)})
          )),
  # Reuse Cycles
  tabItem(tabName = "rCycl", h1("Reuse cycles"), tags$hr(),
          conditionalPanel(condition = 'input.nDataSts == 1',
                           infoBox(width = 12, "More datasets required", color = Hcol('Tertiary')[2], icon = icon("eye-slash"),
                                   h4('Reuse cycles plots require at least two datasets!'))), 
          conditionalPanel(condition = 'input.nDataSts >= 2', 
                           #fluidRow(column(2, selectInput("MP.model", label = "Definition to use:", 
                          #                                choices = list("Batch systems" = 1, "Continous systems" = 2))),
                          #          column(2, h5('Be sure all data has been entered and transformated (if required).'),
                          #                 actionButton("plotReuseButton", label = "Plot reuse cycles", styleclass = 'primary'))),
                           tags$hr(),
                           reuseModuleUI('reusecyclesM'))),
  #Species concentration
  tabItem(tabName = "spCnc", h2("Species concentration")),

  tabItem(tabName = 'exDat', examplesModuleUI('examples')),
  tabItem(tabName = "citation", h1("Citation"), citationModuleUI()),
  tabItem(tabName = "bibliography", h1("Bibliography"), bibliographyModuleUI())
)
