LytDatInput <- tabBox(width = 12, height = 800,
                     tabPanel('Data',
                              fluidRow(inputDataModuleUI('MainDset1', value0 = 7),
                                       conditionalPanel(condition = "input.nSpecies >= 2",
                                                        inputDataModuleUI('SecDset1', Spc = "Secondary", value0 = 4)),
                                       conditionalPanel(condition = "input.nSpecies == 3",
                                                        inputDataModuleUI('TerDset1', Spc = "Tertiary", value0 = 4))),
                              conditionalPanel(condition = 'input.nDataSts >= 2', {
                                fluidRow(inputDataModuleUI('MainDset2', IntID = 2, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset2', Spc = "Secondary", IntID = 2, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset2', Spc = "Tertiary", IntID = 2, value0 = 4)))}),
                              conditionalPanel(condition = 'input.nDataSts >= 3', {
                                fluidRow(inputDataModuleUI('MainDset3', IntID = 3, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset3', Spc = "Secondary", IntID = 3, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset3', Spc = "Tertiary", IntID = 3, value0 = 4)))}),
                              conditionalPanel(condition = 'input.nDataSts >= 4', {
                                fluidRow(inputDataModuleUI('MainDset4', IntID = 4, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset4', Spc = "Secondary", IntID = 4, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset4', Spc = "Tertiary", IntID = 4, value0 = 4)))}),
                              conditionalPanel(condition = 'input.nDataSts >= 5', {
                                fluidRow(inputDataModuleUI('MainDset5', IntID = 5, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset5', Spc = "Secondary", IntID = 5, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset5', Spc = "Tertiary", IntID = 5, value0 = 4)))}),
                              conditionalPanel(condition = 'input.nDataSts >= 6', {
                                fluidRow(inputDataModuleUI('MainDset6', IntID = 6, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset6', Spc = "Secondary", IntID = 6, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset6', Spc = "Tertiary", IntID = 6, value0 = 4)))}),
                              conditionalPanel(condition = 'input.nDataSts >= 7', {
                                fluidRow(inputDataModuleUI('MainDset7', IntID = 7, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset7', Spc = "Secondary", IntID = 7, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset7', Spc = "Tertiary", IntID = 7, value0 = 4)))}),
                              conditionalPanel(condition = 'input.nDataSts >= 8', {
                                fluidRow(inputDataModuleUI('MainDset8', IntID = 8, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset8', Spc = "Secondary", IntID = 8, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset8', Spc = "Tertiary", IntID = 8, value0 = 4)))}),
                              conditionalPanel(condition = 'input.nDataSts >= 9', {
                                fluidRow(inputDataModuleUI('MainDset9', IntID = 9, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset9', Spc = "Secondary", IntID = 9, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset9', Spc = "Tertiary", IntID = 9, value0 = 4)))}),
                              conditionalPanel(condition = 'input.nDataSts >= 10', {
                                fluidRow(inputDataModuleUI('MainDset10', IntID = 10, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset10', Spc = "Secondary", IntID = 10, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset10', Spc = "Tertiary", IntID = 10, value0 = 4)))}),
                              conditionalPanel(condition = 'input.nDataSts >= 10', {
                                fluidRow(inputDataModuleUI('MainDset11', IntID = 11, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset11', Spc = "Secondary", IntID = 11, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset11', Spc = "Tertiary", IntID = 11, value0 = 4)))}),
                              conditionalPanel(condition = 'input.nDataSts >= 12', {
                                fluidRow(inputDataModuleUI('MainDset12', IntID = 12, value0 = 7),
                                         conditionalPanel(condition = "input.nSpecies >= 2",
                                                          inputDataModuleUI('SecDset12', Spc = "Secondary", IntID = 12, value0 = 4)),
                                         conditionalPanel(condition = "input.nSpecies == 3",
                                                          inputDataModuleUI('TerDset12', Spc = "Tertiary", IntID = 12, value0 = 4)))})),
                     tabPanel('Instructions', inputDataDs))