LytPermCoef <- tabBox(width = 12, height = 800,
                      tabPanel('Data',
                               fluidRow(column(2, numericInput("P.area", label = "Membrane area (cm^2)", value = 7.8, min = 0)),
                                        column(2, numericInput("P.vol0", label = "Initial volume (cm^3)", value = 85, min = 0)),
                                        column(2, h5('Be sure all data has been entered and transformated (when required) before proceed.'),
                                               actionButton("calcPrCf", label = "Calculate/recalculate", styleclass = 'primary'))),
                               tags$hr(),
                               permCoefModuleUI('permCoef1'),
                               conditionalPanel(condition = 'input.nDataSts >= 2', {permCoefModuleUI('permCoef2', IntID = 2)}),
                               conditionalPanel(condition = 'input.nDataSts >= 3', {permCoefModuleUI('permCoef3', IntID = 3)}),
                               conditionalPanel(condition = 'input.nDataSts >= 4', {permCoefModuleUI('permCoef4', IntID = 4)}),
                               conditionalPanel(condition = 'input.nDataSts >= 5', {permCoefModuleUI('permCoef5', IntID = 5)}),
                               conditionalPanel(condition = 'input.nDataSts >= 6', {permCoefModuleUI('permCoef6', IntID = 6)}),
                               conditionalPanel(condition = 'input.nDataSts >= 7', {permCoefModuleUI('permCoef7', IntID = 7)}),
                               conditionalPanel(condition = 'input.nDataSts >= 8', {permCoefModuleUI('permCoef8', IntID = 8)}),
                               conditionalPanel(condition = 'input.nDataSts >= 9', {permCoefModuleUI('permCoef9', IntID = 9)}),
                               conditionalPanel(condition = 'input.nDataSts >= 10', {permCoefModuleUI('permCoef10', IntID = 10)}),
                               conditionalPanel(condition = 'input.nDataSts >= 11', {permCoefModuleUI('permCoef11', IntID = 11)}),
                               conditionalPanel(condition = 'input.nDataSts >= 12', {permCoefModuleUI('permCoef12', IntID = 12)})),
                      tabPanel('Instructions', permCoefDs))