LytProfiles <- tabBox(width = 12, height = 800,
                      tabPanel('Data',
                               fluidRow(column(2, selectInput("trendM", label = "Model for the main species profiles",
                                                              choices = list("Paredes et al." = 1, "Rodriguez de San Miguel et al." = 2,
                                                                             "LOESS (non parametric)" = 3, "Linear" = 4, 
                                                                             "No trend line" = 5)),
                                               uiOutput("M.mdlStt")),
                                        column(2, conditionalPanel(condition = "input.nSpecies >= 2",
                                                                   selectInput("trendS", label = "Model for the sec. species profiles",
                                                                               choices = list("Paredes et al." = 1, 
                                                                                              "Rodriguez de San Miguel et al." = 2,
                                                                                              "LOESS (non parametric)" = 3,
                                                                                              "Linear" = 4, "No trend line" = 5)),
                                                                   uiOutput("S.mdlStt"))),
                                        column(2, conditionalPanel(condition = "input.nSpecies >= 3",
                                                                   selectInput("trendT", 
                                                                               label = "Model for the tertiary species profiles",
                                                                               choices = list("Paredes et al." = 1, 
                                                                                              "Rodriguez de San Miguel et al." = 2,
                                                                                              "LOESS (non parametric)" = 3,
                                                                                              "Linear" = 4, "No trend line" = 5)),
                                                                   uiOutput("T.mdlStt"))),
                                        column(2, h5('Be sure all data has been entered and transformated 
                                                     (when required) before proceed.'),
                                               actionButton("plotTrPr", label = "Draw/redraw profiles", styleclass = 'primary'))),
                               tags$hr(),
                               profileModuleUI('transProf1'),
                               conditionalPanel(condition = 'input.nDataSts >= 2', {profileModuleUI('transProf2', IntID = 2)}),
                               conditionalPanel(condition = 'input.nDataSts >= 3', {profileModuleUI('transProf3', IntID = 3)}),
                               conditionalPanel(condition = 'input.nDataSts >= 4', {profileModuleUI('transProf4', IntID = 4)}),
                               conditionalPanel(condition = 'input.nDataSts >= 5', {profileModuleUI('transProf5', IntID = 5)}),
                               conditionalPanel(condition = 'input.nDataSts >= 6', {profileModuleUI('transProf6', IntID = 6)}),
                               conditionalPanel(condition = 'input.nDataSts >= 7', {profileModuleUI('transProf7', IntID = 7)}),
                               conditionalPanel(condition = 'input.nDataSts >= 8', {profileModuleUI('transProf8', IntID = 8)}),
                               conditionalPanel(condition = 'input.nDataSts >= 9', {profileModuleUI('transProf9', IntID = 9)}),
                               conditionalPanel(condition = 'input.nDataSts >= 10', {profileModuleUI('transProf10', IntID = 10)}),
                               conditionalPanel(condition = 'input.nDataSts >= 11', {profileModuleUI('transProf11', IntID = 11)}),
                               conditionalPanel(condition = 'input.nDataSts >= 12', {profileModuleUI('transProf12', IntID = 12)})),
                     tabPanel('Instructions', profileDs))